# Udemy Courses Dataset

* This dataset contains course data for many subjects from the UDEMY site
* We will analyze the data using the Pandas library

### Import libraries and dataframe / csv

In [5]:
import pandas as pd
data = pd.read_csv(r'.\file.csv')
data.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments

In [76]:
#Check for null data
data.isnull().sum()
data.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                  object
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

In [15]:
data.shape #j(3682, 11)

<bound method DataFrame.info of       course_id                                       course_title  is_paid  \
0        288942  #1 Piano Hand Coordination: Play 10th Ballad i...     True
1       1170074  #10 Hand Coordination - Transfer Chord Ballad ...     True
2       1193886  #12 Hand Coordination: Let your Hands dance wi...     True
3       1116700  #4 Piano Hand Coordination: Fun Piano Runs in ...     True
4       1120410  #5  Piano Hand Coordination:  Piano Runs in 2 ...     True
...         ...                                                ...      ...
3677     328960  Your Own Site in 45 Min: The Complete Wordpres...     True
3678     552700    Your Second Course on Piano: Two Handed Playing     True
3679     631754  Zend Framework 2: Learn the PHP framework ZF2 ...     True
3680    1225194  Zoho Books Gestion FinanciÃ¨re d'Entreprise pas...    False
3681     964478                Zombie Apocalypse Photoshop Actions     True

     price  num_subscribers  num_reviews  num_lectures               level  \
0       35             3137           18            68          All Levels
1       75             1593            1            41  Intermediate Level
2       75              482            1            47  Intermediate Level
3       75              850            3            43  Intermediate Level
4       75              940            3            32  Intermediate Level
...    ...              ...          ...           ...                 ...
3677   120             1566           29            36          All Levels
3678    70             1018           12            22      Beginner Level
3679    40              723          130            37          All Levels
3680  Free              229            0            33          All Levels
3681    50               12            1            15          All Levels

     content_duration   published_timestamp              subject
0           1.5 hours  2014-09-18T05:07:05Z  Musical Instruments
1              1 hour  2017-04-12T19:06:34Z  Musical Instruments
2           1.5 hours  2017-04-26T18:34:57Z  Musical Instruments
3              1 hour  2017-02-21T23:48:18Z  Musical Instruments
4             37 mins  2017-02-21T23:44:49Z  Musical Instruments
...               ...                   ...                  ...
3677          4 hours  2015-04-20T22:15:17Z      Web Development
3678          5 hours  2015-10-26T20:04:21Z  Musical Instruments
3679        6.5 hours  2015-11-11T18:55:45Z      Web Development
3680          2 hours  2017-05-26T16:45:55Z     Business Finance
3681        1.5 hours  2016-09-26T22:19:48Z       Graphic Design

[3682 rows x 11 columns]>

### 1. What are all the different subject categories Udemy is offering courses for in this dataset?

In [18]:
data['subject'].unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

### 2. Which subject categories has the maximum number of courses?

In [22]:
data['subject'].value_counts()

subject
Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: count, dtype: int64

### 3. Show all the courses which are Free of Charge

In [35]:
data[data['is_paid'] == False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,Â¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion FinanciÃ¨re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

### 4. Show all the courses that are paid

In [44]:
data[data['is_paid'] == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

### 5. Which are the Top Selling Paid Courses?

In [56]:
data[data.is_paid == True].sort_values('num_subscribers', ascending = False).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
2233,94430,Learn Javascript & JQuery From Scratch,True,30,84897,2685,10,All Levels,2 hours,2013-10-10T15:19:29Z,Web Development
2034,364426,JavaScript: Understanding the Weird Parts,True,175,79612,16976,85,All Levels,11.5 hours,2015-03-12T23:19:54Z,Web Development
2829,238934,Pianoforall - Incredible New Way To Learn Pian...,True,200,75499,7676,362,All Levels,30 hours,2014-08-07T06:27:51Z,Musical Instruments
285,756150,Angular 4 (formerly Angular 2) - The Complete ...,True,190,73783,19649,329,All Levels,22 hours,2016-02-11T07:29:29Z,Web Development
447,11174,Become a Web Developer from Scratch,True,120,69186,2408,197,All Levels,27.5 hours,2011-11-19T21:51:20Z,Web Development
2118,289230,Learn and Understand AngularJS,True,175,59361,11580,55,All Levels,7 hours,2014-09-24T00:57:25Z,Web Development
2119,461160,Learn and Understand NodeJS,True,195,58208,11123,98,All Levels,13 hours,2015-08-31T21:07:48Z,Web Development
3284,556248,The Complete HTML & CSS Course - From Novice T...,True,195,57422,874,84,All Levels,7.5 hours,2015-07-27T16:57:52Z,Web Development

### 6. Which are the lowest selling paid courses

In [65]:
data[data.is_paid == True].sort_values('num_subscribers', ascending = True).head(20)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
491,1251582,Best Practices in Corporate Budgeting,True,50,0,0,9,Intermediate Level,2 hours,2017-06-29T22:01:56Z,Business Finance
2070,1215926,Kickstarter success in 5 easy steps,True,20,0,0,12,All Levels,31 mins,2017-05-16T14:55:28Z,Business Finance
2900,995384,Professional Business Logo Design Using Free O...,True,20,0,0,5,All Levels,37 mins,2016-10-31T16:09:48Z,Graphic Design
1325,1187084,Forex how traders beat the markest with little...,True,100,0,0,16,All Levels,1 hour,2017-07-06T21:16:13Z,Business Finance
2983,1233302,Ratio Analysis for Financial Statements,True,50,0,0,6,Beginner Level,2 hours,2017-07-03T21:39:57Z,Business Finance
994,603902,Curso de Didgeridoo nivel principiante,True,50,0,0,31,Beginner Level,1 hour,2016-04-11T04:14:05Z,Musical Instruments
1931,1247992,Introduction to Project Management for Finance...,True,50,0,0,9,Beginner Level,2 hours,2017-07-03T21:40:32Z,Business Finance
1386,885413,Foundations of Investing,True,40,0,0,18,Beginner Level,2 hours,2016-07-27T21:07:46Z,Business Finance
1910,1157298,Introduction to Forex Trading Business For Beg...,True,20,0,0,27,Beginner Level,1.5 hours,2017-04-23T16:19:01Z,Business Finance
1909,1157298,Introduction to Forex Trading Business For Beg...,True,20,0,0,27,Beginner Level,1.5 hours,2017-04-23T16:19:01Z,Business Finance
1390,1136038,Free Ways to Create Passive Income Online,True,25,0,0,27,Beginner Level,1 hour,2017-04-17T22:33:13Z,Business Finance
403,1221942,Basic Bookkeeping,True,35,0,0,12,Beginner Level,44 mins,2017-05-23T16:20:18Z,Business Finance
98,1219820,Accounting - The 6 most important rules you mu...,True,20,0,0,9,All Levels,1 hour,2017-05-25T21:55:50Z,Business Finance
954,1169196,"Credit concepts and checklist for bankers, cre...",True,20,0,0,10,Beginner Level,2.5 hours,2017-04-24T14:56:01Z,Business Finance
91,1265814,ABRSM Grade III Piano Class - Handel Sonatina ...,True,20,0,0,5,Beginner Level,31 mins,2017-07-06T16:12:34Z,Musical Instruments
3165,1087466,Stop Creditors from Harassing you and Avoid Ba...,True,20,0,0,7,Beginner Level,37 mins,2017-02-02T16:22:37Z,Business Finance
3185,177614,Super Textos con Photoshop,True,20,0,0,8,Beginner Level,2 hours,2014-03-31T20:31:04Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3221,1057040,Teeter-Totter Accounting,True,90,0,0,12,Beginner Level,1 hour,2017-02-08T22:15:56Z,Business Finance

### 7. Show all courses of Graphic Design where the price is below $100

In [94]:
#Initially does not work due to data type of price being set to an object
#data[(data.subject == 'Graphic Design') & (data.price < 100)]
#data['price'].value_counts() --> Assess values before conversions
#data.replace('Free', 0,inplace = True)
#data['price'].value_counts() --> Checking that the conversion worked
#data['price'] = data['price'].astype(float)
data.dtypes #--> Checking that the conversion worked

course_id                int64
course_title            object
is_paid                   bool
price                  float64
num_subscribers          int64
num_reviews              int64
num_lectures             int64
level                   object
content_duration        object
published_timestamp     object
subject                 object
dtype: object

In [98]:
data[(data.subject == 'Graphic Design') & (data.price < 100)].head() #485 courses less than $100

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25.0,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30.0,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20.0,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20.0,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
52,794036,8 Stunden professionelles Cinema 4D Training,True,50.0,18,1,38,All Levels,8.5 hours,2016-03-22T20:51:28Z,Graphic Design

### 8.  List out all the courses that are related with 'Python'

In [105]:
data[data.course_title.str.contains('Python')] #Can use count method to confirm 29 courses in total, or use len

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
216,599504,Advanced Scalable Python Web Development Using...,True,120.0,1299,56,71,Intermediate Level,14 hours,2016-08-11T22:09:24Z,Web Development
777,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195.0,23412,799,251,All Levels,45 hours,2013-04-08T00:46:14Z,Web Development
814,631128,Complete Python Web Course: Build 8 Python Web...,True,110.0,7489,941,173,All Levels,16 hours,2015-11-08T20:57:35Z,Web Development
842,186096,"Core: A Web App Reference Guide for Django, Py...",True,195.0,2497,98,154,All Levels,26 hours,2014-05-29T00:58:43Z,Web Development
1400,394832,Fun and creative web engineering with Python a...,False,0.0,10917,319,25,All Levels,2 hours,2015-06-09T19:51:50Z,Web Development
1932,1038538,Introduction to QGIS Python Programming,True,85.0,197,26,28,Beginner Level,3.5 hours,2016-12-22T00:11:22Z,Web Development
1969,902888,Investment Portfolio Analysis with Python,True,50.0,209,13,37,All Levels,7 hours,2016-07-13T21:40:32Z,Business Finance
2294,391546,Learn Python and Django: Payment Processing,True,70.0,17714,198,23,All Levels,3.5 hours,2015-02-09T15:37:56Z,Web Development
2295,1063722,Learn Python Django - A Hands-On Course,True,50.0,1339,21,18,Beginner Level,2 hours,2017-01-18T21:53:34Z,Web Development
2341,546848,Learn to code in Python and learn Adobe Photos...,True,50.0,1132,1,29,All Levels,2 hours,2015-07-08T00:15:12Z,Graphic Design
2906,368340,Professional Python Web Development Using Flask,True,120.0,3420,489,102,Beginner Level,14.5 hours,2015-03-04T00:10:36Z,Web Development
2908,1035940,Professional RESTful API Design using Python F...,True,120.0,578,25,36,Intermediate Level,4.5 hours,2017-01-11T21:15:25Z,Web Development
2929,270808,Projects in Django and Python,True,60.0,1764,53,28,All Levels,6.5 hours,2014-10-21T07:58:07Z,Web Development
2952,1170894,Python Algo Stock Trading: Automate Your Trading!,True,95.0,1165,21,41,Beginner Level,2.5 hours,2017-05-28T23:41:03Z,Business Finance
2953,1070886,Python Algo Trading: FX Trading with Oanda,True,200.0,453,42,33,Intermediate Level,3 hours,2017-03-14T00:39:45Z,Business Finance
2954,1196544,Python Algo Trading: Sentiment Trading with News,True,200.0,294,19,42,All Levels,7 hours,2017-04-28T16:41:44Z,Business Finance
2955,822444,Python and Django Full Stack Web Developer Boo...,True,200.0,11832,1883,191,All Levels,31.5 hours,2017-02-24T18:40:55Z,Web Development
2956,477702,Python for Beginners: Python Programming Langu...,True,150.0,6153,125,84,Beginner Level,5 hours,2015-06-14T18:18:57Z,Web Development
2957,1035472,Python for Finance: Investment Fundamentals & ...,True,195.0,3811,278,103,All Levels,6.5 hours,2017-03-30T22:17:09Z,Business Finance
2958,529828,Python for Trading & Investing,True,95.0,638,25,36,All Levels,5 hours,2015-06-17T22:23:31Z,Business Finance
2959,70640,Python Programming: Create an Digital Marketpl...,True,195.0,4198,145,161,All Levels,26 hours,2013-10-20T19:53:28Z,Web Development
2960,523312,Python Web Programming,True,100.0,1020,46,60,Beginner Level,6 hours,2015-07-01T21:46:36Z,Web Development
2962,1088656,Quantitative Trading Analysis with Python,True,50.0,256,17,49,All Levels,5.5 hours,2017-01-27T17:11:28Z,Business Finance
3013,970600,REST APIs with Flask and Python,True,110.0,5151,737,115,Intermediate Level,12.5 hours,2016-11-06T19:00:38Z,Web Development
3154,815482,Stock Technical Analysis with Python,True,50.0,409,35,46,All Levels,8 hours,2016-04-12T00:40:03Z,Business Finance
3272,938560,The Complete Ethical Hacking Course 2.0: Pytho...,True,195.0,7827,268,66,All Levels,11 hours,2016-09-26T15:08:29Z,Web Development
3460,76052,Try Django 1.9 | Build a Blog and Learn Python...,True,50.0,7407,172,147,All Levels,20 hours,2014-03-04T07:12:21Z,Web Development
3573,16646,Web Programming with Python,True,50.0,35267,217,53,All Levels,4 hours,2012-04-25T00:01:43Z,Web Development
3574,574082,"Web Scraping with Python, Ruby & import. io",True,75.0,973,50,46,All Levels,4.5 hours,2015-08-09T22:16:41Z,Web Development

### 9. What are the courses published in the year 2015

In [112]:
data['published_timestamp'] = pd.to_datetime(data['published_timestamp'])

In [116]:
data.dtypes #proving the conversion worked

course_id                            int64
course_title                        object
is_paid                               bool
price                              float64
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration                    object
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [122]:
data[data['published_timestamp'].dt.year == 2015] #1014 courses
#Can also add a column for year and then filter, but this way was quicker and still readable

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
10,591880,1 - Concepts of Statistics For Beginners Step ...,True,200.0,273,4,15,Beginner Level,31 mins,2015-08-30 22:48:34+00:00,Business Finance
16,302450,10 Numbers Every Business Owner Should Know,True,20.0,13,1,9,All Levels,1 hour,2015-03-08 19:11:24+00:00,Business Finance
19,384928,101 Blues riffs - learn how the harmonica supe...,True,200.0,1350,65,55,Intermediate Level,6.5 hours,2015-01-04 21:14:31+00:00,Musical Instruments
23,550842,16 Guitar Chords to Jam With - (Beginner - Int...,True,20.0,1224,19,20,Beginner Level,1 hour,2015-07-10 19:53:56+00:00,Musical Instruments
26,486240,2 Easy Steps To Investment And Avoiding Traps,True,20.0,828,1,20,All Levels,1 hour,2015-04-27 23:18:59+00:00,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3675,551170,Your First Course on Piano,True,70.0,2002,34,33,Beginner Level,4 hours,2015-07-16 17:07:49+00:00,Musical Instruments
3676,498488,Your First Successful Forex Trades - With Case...,True,200.0,1079,34,16,All Levels,2.5 hours,2015-05-26 20:48:48+00:00,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120.0,1566,29,36,All Levels,4 hours,2015-04-20 22:15:17+00:00,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70.0,1018,12,22,Beginner Level,5 hours,2015-10-26 20:04:21+00:00,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40.0,723,130,37,All Levels,6.5 hours,2015-11-11 18:55:45+00:00,Web Development

### 10. What are the maximum number of subscribers for each level of courses

In [125]:
#First, let's just use value counts
data.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35.0,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments

In [129]:
data['level'].value_counts() #entries in total, not subscribers, but some initial indicator of data shape for confirmation

level
All Levels            1932
Beginner Level        1271
Intermediate Level     421
Expert Level            58
Name: count, dtype: int64

In [131]:
data.groupby('level')['num_subscribers'].sum() #This is all subscribers across all courses

level
All Levels            6916112
Beginner Level        4052843
Expert Level            50196
Intermediate Level     742005
Name: num_subscribers, dtype: int64

In [135]:
data.groupby('level')['num_subscribers'].max() #max subscribers to a single course within each category

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [139]:
data[data['num_subscribers'] == 268923] #example course lookup based on All levels

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,0.0,268923,8629,45,All Levels,10.5 hours,2013-02-14 07:03:41+00:00,Web Development

In [141]:
data[data['num_subscribers'] == 161029] #example course lookup based on Beginner levels

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
776,59014,Coding for Entrepreneurs Basic,False,0.0,161029,279,27,Beginner Level,3.5 hours,2013-06-09 15:51:55+00:00,Web Development